# Generated by Django 4.2.7 on 2025-08-25 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_enhanced_tasks_and_leave_management'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='original_stage',
            field=models.ForeignKey(blank=True, help_text='Original stage for subtasks', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='original_tasks', to='dashboard.taskstage'),
        ),
    ]
